### ISSUE TITLE
ValueError when trying to run edify.py

### ISSUE THREAD

**Issue by HalfFinn52** [veebch/edify#4]
Hi,

I have been trying to run your excellent project, as listed in Make magazine and also here on GitHub.  When I try to run the script I get the following error(s):

pi@rpiquotes:~/edify $ python3 edify.py
Traceback (most recent call last):
  File "/home/pi/edify/edify.py", line 21, in <module>
    import pandas as pd 
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/__init__.py", line 29, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 44 from C header, got 40 from PyObject

There is one change in my hardware compared to the setup in the Make Magazine.  I am using a Pi Zero 2W instead of the original Pi Zero - would that cause this problem?

Thanks.

**Comment by veebch** [comment]
Hey there, I'll try to reproduce it. It looks like pandas is complaining....
In the meantime, try `python3 -m pip install --upgrade pandas`
It will give the version a bump.

**Comment by HalfFinn52** [comment]
Ok thanks - I'll try that.  I didn't really think it was the issue, but I did try it on a original Pi Zero and got the same error.

**Comment by HalfFinn52** [comment]
Upgraded pandas and got a similar error:

Successfully installed pandas-1.4.1
pi@rpiquotes:~ $ cd edify
pi@rpiquotes:~/edify $ python3 edify.py
Traceback (most recent call last):
  File "/home/pi/edify/edify.py", line 21, in <module>
    import pandas as pd 
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa:F401
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 48 from C header, got 40 from PyObject

**Comment by veebch** [comment]
Reproduced it! And then fixed it...

python3 -m pip install --upgrade numpy

**Comment by veebch** [comment]
Just updating the requirements.txt now! Thanks for flagging this up :)

**Comment by HalfFinn52** [comment]
Making progress but now I get this message in the terminal and no display to the e-Paper:
pi@rpiquotes:~/edify $ python3 edify.py
INFO:root:['redditquotes', 'textfileflash', 'wordaday']
INFO:root:get reddit quotes
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.reddit.com:443
DEBUG:urllib3.connectionpool:https://www.reddit.com:443 "GET /r/quotes/top/.json?t=week&limit=100 HTTP/1.1" 200 25948
kind
data
Count=2
2 or more quotes - split after last one
"The best way to predict the future is to create it." ~ - Abraham Lincoln
 Abraham Lincoln
INFO:root:[Errno 2] No such file or directory

**Comment by veebch** [comment]
Progress! :)

Did you make a copy of config_example.yaml with the command:
`cp config_example.yaml config.yaml`

**Comment by HalfFinn52** [comment]
Yes.  just to make sure - I remove the config.yaml and redid the copy command.  Same problem.  By the way, the way my e-Paper is oriented is upside down to your pictures.  I am assuming that I can set invert to true to accommodate this?

**Comment by veebch** [comment]
Hmmm, I just ran it on a fresh install of raspios. Is the epaper a waveshare screen?

**Comment by veebch** [comment]
It could be that spi isn't enabled. If you run `sudo raspi-config` and then select Interface Options and make sure SPI is enabled, that might do it

**Comment by HalfFinn52** [comment]
I feel really stupid.  As one of my attempts to get things running, I wiped the SD card and started all over but, I forgot the step to enable the SPI.  That fixed it.

Thanks for all your help.

Ed

**Comment by veebch** [comment]
(I added a flip option to the example config.yaml... do another pull and give it a try... tested it here and it works)

**Comment by HalfFinn52** [comment]
Perfect!  Flip works great.

Thanks again!

**Comment by battysakis** [comment]
Thank you for this. I’m up and running!
![40D5A506-6051-4B3D-A7CF-F03C300F77B6](https://user-images.githubusercontent.com/99562505/153985853-a071e7f7-e5b2-42a0-a7ba-a0233c5000aa.jpeg)

**Comment by veebch** [comment]
Excellent work! You may already know this, but I didn't realise at first: if you pull the green plastic tab, then the screen protector comes off and the screen is a nice matt texture.
